[profile.default]
src = 'src'
out = 'out'
fs_permissions = [{ access = "read", path = "./"}]
libs = ['lib']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
